version: '3.8'

services:
  aerospike:
    image: aerospike:ce-6.0.0.2
    container_name: airospike-local
    restart: always
    ports:
      - "3000-3002:3000-3002"
    volumes:
      - "./aerospike-db-data:/opt/aerospike/etc/"
      - "./aero_config:/config_folder"

    command: ["--config-file","/config_folder/custom.conf"]

   
volumes:
  aerospike-db-data:
  aero_config:
