version: '3.8'

services:
  aerospike:
    image: aerospike/aerospike-server
    environment:
      - NAMESPACE=adfalcon
      - MEM_GB=1
    restart: always
    ports:
      - "3000-3002:3000-3002"
    volumes:
      - "./aerospike-db-data:/opt/aerospike/etc/"

volumes:
  aerospike-db-data: