version: '3.8'

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    network_mode: host
    image: prom/prometheus:latest
    container_name: prometheus
    # ports:
    #   - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  # extra_hosts:
  #   - "host.docker.internal:host-gateway"