version: "3.8"

services:
  sqlServerDb:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - ./postgres_db-data:/var/lib/postgresql/data/



volumes: 
  db-data: